; Uncomment and configure mode https://xdebug.org/docs/all_settings#xdebug.mode
;zend_extension=xdebug.so
;xdebug.client_host=host.docker.internal
;xdebug.client_host=172.15.198.110
;xdebug.client_host=192.168.1.5
;xdebug.start_with_request=yes
;xdebug.mode=debug
;xdebug.idekey=PHPSTORM