; a pool called www
[www]
user = www-data
group = www-data


; use a unix domain socket
;listen = /var/run/php/php8.2-fpm.sock

; or listen on a TCP connection
listen = 127.0.0.1:9000
date.timezone=Europe/Moscow
memory_limit=512M
upload_max_filesize = 50M
; Must be greater than or equal to upload_max_filesize
post_max_size = 50M

; //seconds 1 hour + 5 minutes
session.gc_maxlifetime = 3900
session.cookie_lifetime = 3900

;session.gc_maxlifetime = 15
;session.cookie_lifetime = 15