server {
    listen       80;
    charset utf-8;
    server_name localhost;
    root /usr/share/nginx/html/yii-books/web;
    index index.php;
    client_max_body_size 128M;

    # optionally disable falling back to PHP script for the asset directories;
    # nginx will return a 404 error when files are not found instead of passing the
    # request to Symfony (improves performance but Symfony's 404 page is not displayed)
    # location /bundles {
    #     try_files $uri =404;
    # }

    # optionally disable falling back to PHP script for the asset directories;
    # nginx will return a 404 error when files are not found instead of passing the
    # request to Symfony (improves performance but Symfony's 404 page is not displayed)
    # location /bundles {
    #     try_files $uri =404;
    # }

    location / {
        # Redirect everything that is not a real file to index.php
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # Deny access to .htaccess, .git, .svn, etc.
    location ~ /\.(ht|svn|git) {
        deny all;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass 127.0.0.1:9000; # Adjust to your PHP-FPM socket or port
        #fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
        try_files $uri =404;
    }

    # Avoid processing static files through Yii
    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires max;
        log_not_found off;
    }

    #location ~ ^/(ru|en)/admin/import-of-companies(/?)$ {
    #    keepalive_timeout 5s;
    #    send_timeout 5s;
    #    client_body_timeout 5s;
    #    #client_header_timeout 5s;
    #    proxy_connect_timeout 5s;
    #    proxy_read_timeout 5s;
    #    proxy_send_timeout 5s;
    #    fastcgi_connect_timeout 5s;
    #    fastcgi_read_timeout 5s;
    #    fastcgi_send_timeout 5s;
    #    memcached_connect_timeout 5s;
    #    memcached_read_timeout 5s;
    #    memcached_send_timeout 5s;

    #    try_files $uri /index.php$is_args$args;
    #}


    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
